# Generated by Django 6.0.3 on 2026-04-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=3000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('Poductype', models.CharField(choices=[('FOOD', 'Food'), ('FILTER', 'Filter'), ('OXYGEN_PUMP', 'Oxygen Pump'), ('TOYS', 'Toys'), ('SOBO', 'Sobo'), ('AQUARIUM', 'aquarium'), ('DECORATION', 'decoration'), ('OTHER', 'other')], max_length=100)),
                ('Brand', models.CharField(choices=[('Optimum', 'Optimum'), ('Toya', 'Toya'), ('Taiyo', 'Taiyo'), ('Sobo', 'Sobo')], max_length=100)),
                ('SubCtgry', models.CharField(blank=True, choices=[('DRY', 'Dry'), ('FROZEN', 'Frozen'), ('INTERNAL', 'Internal'), ('SPONGE', 'Sponge'), ('STONES', 'Stones'), ('TOYS', 'Toys'), ('CANISTER', 'Canister'), ('HANGON', 'hangon'), ('SUMP', 'sump'), ('WALLPAPER', 'wallpaper'), ('ARTIFICIALPLANTS', 'artificalplants'), ('OTHER', 'other')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='post_files/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.posts')),
            ],
        ),
    ]
